# replace default config
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype: false
  - removeXMLProcInst: false
  - removeXMLStandaloneNo: true
  - removeComments: false
  - removeMetadata: true
  - removeEditorsNSData: false
  - cleanupAttrs: true
  - convertStyleToAttrs: false
  - cleanupIDs: false
  - removeRasterImages: false
  - removeUselessDefs: false
  - cleanupNumericValues: false
  - cleanupListOfValues: false
  - convertColors: false
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: false
  - removeUselessStrokeAndFill: true
  - removeViewBox: false
  - cleanupEnableBackground: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - convertShapeToPath: false
  - moveElemsAttrsToGroup: false
  - moveGroupAttrsToElems: false
  - collapseGroups: false
  - convertPathData: false
  - convertTransform: false
  - removeEmptyAttrs: false
  - removeEmptyContainers: false
  - mergePaths: false
  - removeUnusedNS: true
  - transformsWithOnePath: false
  - addFillStrokeClass: true
  - removeStyleAttr: true
  - sortAttrs: true
  - removeTitle: false
  - removeDesc: false
